package com.shop.db.dao;

import com.shop.db.domain.ShopPermission;
import com.shop.db.domain.ShopPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    long countByExample(ShopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int deleteByExample(ShopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int insert(ShopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int insertSelective(ShopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    ShopPermission selectOneByExample(ShopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    ShopPermission selectOneByExampleSelective(@Param("example") ShopPermissionExample example, @Param("selective") ShopPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    List<ShopPermission> selectByExampleSelective(@Param("example") ShopPermissionExample example, @Param("selective") ShopPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    List<ShopPermission> selectByExample(ShopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    ShopPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    ShopPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    ShopPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopPermission record, @Param("example") ShopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopPermission record, @Param("example") ShopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}