package com.shop.db.dao;

import com.shop.db.domain.ShopAd;
import com.shop.db.domain.ShopAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    long countByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int deleteByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int insert(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int insertSelective(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    ShopAd selectOneByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    ShopAd selectOneByExampleSelective(@Param("example") ShopAdExample example, @Param("selective") ShopAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    List<ShopAd> selectByExampleSelective(@Param("example") ShopAdExample example, @Param("selective") ShopAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    List<ShopAd> selectByExample(ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    ShopAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    ShopAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    ShopAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopAd record, @Param("example") ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopAd record, @Param("example") ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}