package com.shop.db.dao;

import com.shop.db.domain.ShopAddress;
import com.shop.db.domain.ShopAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    long countByExample(ShopAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int deleteByExample(ShopAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int insert(ShopAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int insertSelective(ShopAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    ShopAddress selectOneByExample(ShopAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    ShopAddress selectOneByExampleSelective(@Param("example") ShopAddressExample example, @Param("selective") ShopAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    List<ShopAddress> selectByExampleSelective(@Param("example") ShopAddressExample example, @Param("selective") ShopAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    List<ShopAddress> selectByExample(ShopAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    ShopAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    ShopAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    ShopAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopAddress record, @Param("example") ShopAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopAddress record, @Param("example") ShopAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}