package com.shop.db.dao;

import com.shop.db.domain.ShopCollect;
import com.shop.db.domain.ShopCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    long countByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int deleteByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int insert(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int insertSelective(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    ShopCollect selectOneByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    ShopCollect selectOneByExampleSelective(@Param("example") ShopCollectExample example, @Param("selective") ShopCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    List<ShopCollect> selectByExampleSelective(@Param("example") ShopCollectExample example, @Param("selective") ShopCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    List<ShopCollect> selectByExample(ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    ShopCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopCollect.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    ShopCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    ShopCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopCollect record, @Param("example") ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopCollect record, @Param("example") ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}