package com.shop.db.dao;

import com.shop.db.domain.ShopOrderGoods;
import com.shop.db.domain.ShopOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    long countByExample(ShopOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(ShopOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int insert(ShopOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(ShopOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    ShopOrderGoods selectOneByExample(ShopOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    ShopOrderGoods selectOneByExampleSelective(@Param("example") ShopOrderGoodsExample example, @Param("selective") ShopOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    List<ShopOrderGoods> selectByExampleSelective(@Param("example") ShopOrderGoodsExample example, @Param("selective") ShopOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    List<ShopOrderGoods> selectByExample(ShopOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    ShopOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    ShopOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    ShopOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopOrderGoods record, @Param("example") ShopOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopOrderGoods record, @Param("example") ShopOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}