package com.shop.db.dao;

import com.shop.db.domain.ShopGoodsProduct;
import com.shop.db.domain.ShopGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    long countByExample(ShopGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(ShopGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int insert(ShopGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(ShopGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    ShopGoodsProduct selectOneByExample(ShopGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    ShopGoodsProduct selectOneByExampleSelective(@Param("example") ShopGoodsProductExample example, @Param("selective") ShopGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    List<ShopGoodsProduct> selectByExampleSelective(@Param("example") ShopGoodsProductExample example, @Param("selective") ShopGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    List<ShopGoodsProduct> selectByExample(ShopGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    ShopGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    ShopGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    ShopGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopGoodsProduct record, @Param("example") ShopGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopGoodsProduct record, @Param("example") ShopGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}