package com.shop.db.dao;

import com.shop.db.domain.ShopOrder;
import com.shop.db.domain.ShopOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    long countByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int deleteByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int insert(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int insertSelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    ShopOrder selectOneByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    ShopOrder selectOneByExampleSelective(@Param("example") ShopOrderExample example, @Param("selective") ShopOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    List<ShopOrder> selectByExampleSelective(@Param("example") ShopOrderExample example, @Param("selective") ShopOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    List<ShopOrder> selectByExample(ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    ShopOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    ShopOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    ShopOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopOrder record, @Param("example") ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopOrder record, @Param("example") ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}