package com.shop.db.dao;

import com.shop.db.domain.ShopCategory;
import com.shop.db.domain.ShopCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    long countByExample(ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int deleteByExample(ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int insert(ShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int insertSelective(ShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    ShopCategory selectOneByExample(ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    ShopCategory selectOneByExampleSelective(@Param("example") ShopCategoryExample example, @Param("selective") ShopCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    List<ShopCategory> selectByExampleSelective(@Param("example") ShopCategoryExample example, @Param("selective") ShopCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    List<ShopCategory> selectByExample(ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    ShopCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    ShopCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    ShopCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopCategory record, @Param("example") ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopCategory record, @Param("example") ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}