package com.shop.db.dao;

import com.shop.db.domain.ShopUser;
import com.shop.db.domain.ShopUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    long countByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int deleteByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int insert(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int insertSelective(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    ShopUser selectOneByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    ShopUser selectOneByExampleSelective(@Param("example") ShopUserExample example, @Param("selective") ShopUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    List<ShopUser> selectByExampleSelective(@Param("example") ShopUserExample example, @Param("selective") ShopUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    List<ShopUser> selectByExample(ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    ShopUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    ShopUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    ShopUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopUser record, @Param("example") ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopUser record, @Param("example") ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}