package com.shop.db.dao;

import com.shop.db.domain.ShopAdmin;
import com.shop.db.domain.ShopAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    long countByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int deleteByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int insert(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int insertSelective(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    ShopAdmin selectOneByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    ShopAdmin selectOneByExampleSelective(@Param("example") ShopAdminExample example, @Param("selective") ShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    List<ShopAdmin> selectByExampleSelective(@Param("example") ShopAdminExample example, @Param("selective") ShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    List<ShopAdmin> selectByExample(ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    ShopAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    ShopAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    ShopAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopAdmin record, @Param("example") ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopAdmin record, @Param("example") ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}