package com.shop.db.dao;

import com.shop.db.domain.ShopLog;
import com.shop.db.domain.ShopLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    long countByExample(ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int deleteByExample(ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int insert(ShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int insertSelective(ShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    ShopLog selectOneByExample(ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    ShopLog selectOneByExampleSelective(@Param("example") ShopLogExample example, @Param("selective") ShopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    List<ShopLog> selectByExampleSelective(@Param("example") ShopLogExample example, @Param("selective") ShopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    List<ShopLog> selectByExample(ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    ShopLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    ShopLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    ShopLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopLog record, @Param("example") ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopLog record, @Param("example") ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}