package com.shop.db.dao;

import com.shop.db.domain.ShopSystem;
import com.shop.db.domain.ShopSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    long countByExample(ShopSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int deleteByExample(ShopSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int insert(ShopSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int insertSelective(ShopSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    ShopSystem selectOneByExample(ShopSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    ShopSystem selectOneByExampleSelective(@Param("example") ShopSystemExample example, @Param("selective") ShopSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    List<ShopSystem> selectByExampleSelective(@Param("example") ShopSystemExample example, @Param("selective") ShopSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    List<ShopSystem> selectByExample(ShopSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    ShopSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopSystem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    ShopSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    ShopSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopSystem record, @Param("example") ShopSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopSystem record, @Param("example") ShopSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}