package com.shop.db.dao;

import com.shop.db.domain.ShopRegion;
import com.shop.db.domain.ShopRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    long countByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int deleteByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int insert(ShopRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int insertSelective(ShopRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    ShopRegion selectOneByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    ShopRegion selectOneByExampleSelective(@Param("example") ShopRegionExample example, @Param("selective") ShopRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    List<ShopRegion> selectByExampleSelective(@Param("example") ShopRegionExample example, @Param("selective") ShopRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    List<ShopRegion> selectByExample(ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    ShopRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    ShopRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopRegion record, @Param("example") ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopRegion record, @Param("example") ShopRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopRegion record);
}