package com.shop.db.dao;

import com.shop.db.domain.ShopIssue;
import com.shop.db.domain.ShopIssueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    long countByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int deleteByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int insert(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int insertSelective(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    ShopIssue selectOneByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    ShopIssue selectOneByExampleSelective(@Param("example") ShopIssueExample example, @Param("selective") ShopIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    List<ShopIssue> selectByExampleSelective(@Param("example") ShopIssueExample example, @Param("selective") ShopIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    List<ShopIssue> selectByExample(ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    ShopIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShopIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    ShopIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    ShopIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopIssue record, @Param("example") ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopIssue record, @Param("example") ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ShopIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}